### PR TITLE
Creating a balanced Catalyst reaction

### PR DESCRIPTION
**Pull request by LalitChauhan56**
This adds the functionality of creating a balanced Catalyst reaction.
All we need to do is define the parameters and variables, no need to define the species using the @species macro as they are created automatically! :)
We need to give the input of the reaction in a string format and the create_balanced_reaction function uses it to create a catalyst reaction and automatically balances it stoichiometrically.

Example usage -
```
@parameters k
@variables t

julia> reaction = create_balanced_reaction("CO2 + H2O --> C6H12O6 + O2")
k, 6CO2 + 6H2O --> C6H12O6 + 6*O2

julia> typeof(reaction)
Reaction{Any, Int64}

julia> rn = Catalyst.make_empty_network()
Model ##ReactionSystem#295
States (0):
Parameters (0):

julia> addreaction!(rn,reaction)
1

julia> reactions(rn)
1-element Vector{Reaction}:
k, 6CO2 + 6H2O --> C6H12O6 + 6*O2
```

@anandijain

### CODE REVIEW

**Comment by isaacsas** [comment]
Why use a string based approach instead of Symbolics? 

For example, you could have something like
```julia
Using Catalyst, TestPackage
@variables t
@species C(t) O(t)
@compound CO2(t) = C + 2O   
```
where `CO2(t)` is just a species itself but has additional Symbolics metadata indicating it is a compound, i.e 
```julia
iscompound(CO2) == true
```
and stores the info about its composition (with an API you provide for querying and accessing this data), i.e.
```julia
components(CO2) == [C, O]
coefficient(O, CO2) == 2   
```

Then you could just build Catalyst `Reaction`s involving `CO2`, and apply `balance` to a `Reaction` to return a new balanced `Reaction`.

@anandijain do you see any disadvantage to this approach?

One could still always support the string interface by parsing it and generating such symbolics in the background, but this would allow people to programmatically make and use compounds within the Symbolics setting.

**Comment by isaacsas** [comment]
I actually like this idea more and more as I think about it, and think it should actually just be in Catalyst. I could see this potentially being useful for modeling proteins that are formed of many subunits as a compound.

**Comment by isaacsas** [comment]
We could look at how this is handled in BNGL. I think it allows expressing such concepts I believe.

**Comment by TorkelE** [comment]
Internally it shouldn't be that hard to handle, it could be in the metadata or we create a new field. 

When creating things programmatically with symbols it shouldn't be hard to do, maybe you could do something like
```julia
@variable t
@species X Y
@composite_species XY = X Y
```
In the macro it would be more difficult, but given that we already have this additional syntax we could do something like:
```julia
@reaction_network begin
  @species X Y
  @composite_species XY = X Y
  (kB,kD), X + Y <--> XY
end
```

**Comment by isaacsas** [comment]
I think it should be metadata so it propagates through with the symbolic variables and is accessible downstream just from the symbolic.

**Comment by LalitChauhan56** [comment]
I used the string approach because I couldn't find any existing way in Catalyst to actually define a compound which holds the   values of the species it is composed of.

For example-

`@species H2(t) O2(t) H2O(t) 
#Gave a single new species H2O (Couldn't specify that is made up of H2 and O2)`

But now that I think of it your approach seems better. @isaacsas 

Defining a compound which holds the metadata of the compounds it is composed of makes things a lot more simpler and also that all of it uses Symbolics instead of the string approach. I think it will be better to go with your approach.

**Comment by LalitChauhan56** [comment]
I used the string approach because I couldn't find any existing way in Catalyst to actually define a compound which holds the   values of the species it is composed of.

For example-

`@species H2(t) O2(t) H2O(t) 
#Gave a single new species H2O (Couldn't specify that is made up of H2 and O2)`

But now that I think of it your approach seems better. @isaacsas 

Defining a compound which holds the metadata of the compounds it is composed of makes things a lot more simpler and also that all of it uses Symbolics instead of the string approach which defines symbols in the background. I think it will be better to go with your approach.

**Comment by isaacsas** [comment]
@LalitChauhan56 why don't you finish this PR with your current interface, and then you can tackle the Symbolics-based interface as a followup?

For the interface we'd probably want to support lists of compound / composite species too like
```
@species A(t) B(t) C(t)
@compounds begin
     AB = A + B
     A2C2 = 2A + 2C
...
end        # or @composite_species, we can bikeshed the name later...
```

**Comment by LalitChauhan56** [comment]
I will merge this PR for now as you said. I will define the @compound in the follow-up PR which does all of the stuff discussed above.

**Comment by isaacsas** [comment]
I wouldn't merge the PR until it has been reviewed (I assume @anandijain is planning to look at it?).

**Comment by LalitChauhan56** [comment]
@isaacsas Follow up for the symbolics interface. #9

**Comment by LalitChauhan56** [comment]
Moved over to https://github.com/SciML/Catalyst.jl/pull/657

**Pull request closed without merging**
