### PR TITLE
Adds @compound macro

### PR DESCRIPTION
**Pull request by LalitChauhan56**
Can be used to define compounds which are composed of smaller species. The created compound is also a species.

```
julia> @variables t
@parameters k
@species C(t) H(t) O(t) #Define species

julia> @compound C6H12O2(t),[6C,12H,2O] #Creates a compound(also a species in itself)
3-element Vector{Num}:
  6C(t)
 12H(t)
  2O(t)
  
julia> iscompound(C6H12O2)
true
```

### CODE REVIEW

**Comment by LalitChauhan56** [comment]
Work to be done-
Add functions to query the composition of compound and coefficient of the smaller species it is composed of.
Add support for lists of compounds using begin and end.

**Comment by TorkelE** [comment]
Would it be cleaner and more similar to current standard to drop a couple of `,`? E.g.  something like:
```
@compound C6H12O2(t) [6C, 12H, 2O]
@compound C6H12O2(t): 6C 12H 2O
@compound C6H12O2(t) 6C 12H 2O
```
Not really a priority at this stage, but something to think about at some point.

**Comment by LalitChauhan56** [comment]
Will fix this in the next commit

**Review by isaacsas — CHANGES_REQUESTED** [review]
@LalitChauhan56 let's open this on Catalyst as I suggested in a file `src/compound.jl`.

We also want to make sure this works with interpolation, so stuff like
```julia
@variables t
@species A(t) B(t)
@compound A2B3, [2*$A, 3*$B]
```
works.

**Comment by isaacsas** [comment]
FWIW, I like these options
```julia
@compound C6H12O2(t) 6C 12H 2O
@compound C6H12O2(t) = 6C 12H 2O
```

**Comment by LalitChauhan56** [comment]
Okay, opening this PR on catalyst shortly, doing changes currently to be able to use the macro like 
`@compound C6H12O2(t) 6C 12H 2O
`

**Comment by isaacsas** [comment]
Sounds good!

**Comment by LalitChauhan56** [comment]
Opened up a new [PR](https://github.com/SciML/Catalyst.jl/pull/651) on Catalyst along with the suggested input format for the macro.

**Comment by LalitChauhan56** [comment]
Moved over and merged at https://github.com/SciML/Catalyst.jl/pull/651

**Pull request closed without merging**
